name: campus_app
description: A campus app for students and teachers

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  http: ^0.13.5
  shared_preferences: ^2.1.0
  intl: ^0.18.0
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.5
  image_picker: ^0.8.7+4
  path_provider: ^2.0.14
  url_launcher: ^6.1.10
  flutter_local_notifications: ^14.0.0+1
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
      - lib/assets/logo.jpeg
  

